export interface FlightRequestRow {
  id: string;
  route_from: string;
  route_to: string;
  departure_date: string;
  departure_time: string;
  passengers: number;
  cargo_weight_kg: number | null;
  preferred_aircraft_category: string | null;
  flexibility_hours: number | null;
  special_requests: string | null;
  status_ops: string;
  status_sales: string;
  assigned_ops_id: string | null;
  assigned_ops_name: string | null;
  submitted_to_ops_at: string | null;
  sla_satisfied_at: string | null;
  lead_id: string | null;
  quotation_id: string | null;
  options_status: string | null;
  created_by: string;
  quotation_approval_status: string;
  quotation_approval_option_id: string | null;
  quotation_approval_requested_at: string | null;
  quotation_approval_requested_by: string | null;
  quotation_approval_decided_at: string | null;
  quotation_approval_decided_by: string | null;
  quotation_approval_notes: string | null;
  quotation_issued_at: string | null;
  client_confirmed_at: string | null;
  client_confirmed_by: string | null;
  client_confirmation_late_justification: string | null;
  client_confirmation_evidence_path: string | null;
  client_confirmation_evidence_name: string | null;
  operator_hold_placed: boolean;
  operator_hold_placed_at: string | null;
  operator_hold_placed_by: string | null;
  operator_contract_path: string | null;
  operator_contract_name: string | null;
  operator_contract_uploaded_at: string | null;
  operator_contract_uploaded_by: string | null;
  client_contract_path: string | null;
  client_contract_name: string | null;
  client_contract_uploaded_at: string | null;
  client_contract_uploaded_by: string | null;
  client_contract_signed_at: string | null;
  client_contract_signed_by: string | null;
  unable_to_source_at: string | null;
  unable_to_source_by: string | null;
  unable_to_source_reason: string | null;
}
