import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { MentionField } from '@/components/mentions/MentionField';
import { extractMentionedUserIds, notifyMentionedUsers } from '@/components/mentions/mentionUtils';
import { 
  FileText, 
  Plus, 
  Search,
  DollarSign,
  Plane,
  Calendar,
  Clock,
  Calculator
} from 'lucide-react';

export default function Quotations() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState('');
  const [isQuoteDialogOpen, setIsQuoteDialogOpen] = useState(false);
  const [isRateCardDialogOpen, setIsRateCardDialogOpen] = useState(false);
  const [quoteNotes, setQuoteNotes] = useState('');

  const { data: profiles = [] } = useQuery({
    queryKey: ['profiles-owners'],
    queryFn: async () => {
      const { data, error } = await supabase.from('profiles').select('user_id, full_name, email').order('full_name');
      if (error) throw error;
      return data;
    },
  });

  // Fetch quotes
  const { data: quotes = [], isLoading: quotesLoading } = useQuery({
    queryKey: ['quotes'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('quotes')
        .select('*, aircraft(tail_number, aircraft_type), rate_cards(name)')
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  // Fetch rate cards
  const { data: rateCards = [], isLoading: rateCardsLoading } = useQuery({
    queryKey: ['rate_cards'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rate_cards')
        .select('*')
        .order('name');
      if (error) throw error;
      return data;
    },
  });

  // Fetch aircraft for quote creation
  const { data: aircraft = [] } = useQuery({
    queryKey: ['aircraft'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('aircraft')
        .select('*')
        .eq('status', 'available')
        .order('tail_number');
      if (error) throw error;
      return data;
    },
  });

  // Create quote mutation
  const createQuote = useMutation({
    mutationFn: async (quoteData: {
      aircraft_id: string;
      rate_card_id: string;
      route_from: string;
      route_to: string;
      departure_date: string;
      return_date?: string;
      passengers: number;
      flight_hours: number;
      notes?: string;
    }) => {
      // Calculate pricing based on rate card
      const rateCard = rateCards.find(rc => rc.id === quoteData.rate_card_id);
      if (!rateCard) throw new Error('Rate card not found');

      const basePrice = Number(rateCard.hourly_rate) * Math.max(quoteData.flight_hours, Number(rateCard.minimum_hours) || 2);
      const fuelSurcharge = basePrice * (Number(rateCard.fuel_surcharge_percent) || 0) / 100;
      const repositioningCosts = Number(rateCard.repositioning_fee) || 0;
      const landingFees = Number(rateCard.landing_fee_estimate) || 0;
      const handlingFees = Number(rateCard.handling_fee_estimate) || 0;
      const totalPrice = basePrice + fuelSurcharge + repositioningCosts + landingFees + handlingFees;

      const { data, error } = await supabase
        .from('quotes')
        .insert([{
          ...quoteData,
          quote_number: '', // Auto-generated by trigger
          base_price: basePrice,
          fuel_surcharge: fuelSurcharge,
          repositioning_costs: repositioningCosts,
          landing_fees: landingFees,
          handling_fees: handlingFees,
          total_price: totalPrice,
          created_by: user?.id,
          valid_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        }])
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: async (data) => {
      queryClient.invalidateQueries({ queryKey: ['quotes'] });
      setIsQuoteDialogOpen(false);
      toast.success('Quote created successfully');

      const mentionedIds = extractMentionedUserIds(quoteNotes, profiles).filter((uid) => uid !== user?.id);
      if (mentionedIds.length > 0) {
        await notifyMentionedUsers(mentionedIds, {
          title: 'You were mentioned',
          message: `${user?.name || 'Someone'} mentioned you in notes for quote #${data.quote_number || data.id}`,
          sourceTable: 'quotes',
          sourceId: data.id,
        });
      }
      setQuoteNotes('');
    },
    onError: (error) => {
      toast.error('Failed to create quote: ' + error.message);
    },
  });

  // Create rate card mutation
  const createRateCard = useMutation({
    mutationFn: async (rateCardData: {
      name: string;
      aircraft_type: string;
      hourly_rate: number;
      minimum_hours: number;
      repositioning_fee: number;
      crew_overnight_rate: number;
      fuel_surcharge_percent: number;
      landing_fee_estimate: number;
      handling_fee_estimate: number;
    }) => {
      const { data, error } = await supabase
        .from('rate_cards')
        .insert([{ ...rateCardData, created_by: user?.id }])
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['rate_cards'] });
      setIsRateCardDialogOpen(false);
      toast.success('Rate card created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create rate card: ' + error.message);
    },
  });

  const handleCreateQuote = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    createQuote.mutate({
      aircraft_id: formData.get('aircraft_id') as string,
      rate_card_id: formData.get('rate_card_id') as string,
      route_from: formData.get('route_from') as string,
      route_to: formData.get('route_to') as string,
      departure_date: formData.get('departure_date') as string,
      return_date: formData.get('return_date') as string || undefined,
      passengers: Number(formData.get('passengers')),
      flight_hours: Number(formData.get('flight_hours')),
      notes: quoteNotes,
    });
  };

  const handleCreateRateCard = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    createRateCard.mutate({
      name: formData.get('name') as string,
      aircraft_type: formData.get('aircraft_type') as string,
      hourly_rate: Number(formData.get('hourly_rate')),
      minimum_hours: Number(formData.get('minimum_hours')) || 2,
      repositioning_fee: Number(formData.get('repositioning_fee')) || 0,
      crew_overnight_rate: Number(formData.get('crew_overnight_rate')) || 0,
      fuel_surcharge_percent: Number(formData.get('fuel_surcharge_percent')) || 0,
      landing_fee_estimate: Number(formData.get('landing_fee_estimate')) || 0,
      handling_fee_estimate: Number(formData.get('handling_fee_estimate')) || 0,
    });
  };

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      draft: 'bg-muted text-muted-foreground',
      sent: 'bg-accent text-accent-foreground',
      accepted: 'bg-success text-success-foreground',
      rejected: 'bg-destructive text-destructive-foreground',
      expired: 'bg-warning text-warning-foreground',
      converted: 'bg-success text-success-foreground',
    };
    return colors[status] || 'bg-muted text-muted-foreground';
  };

  const filteredQuotes = quotes.filter(quote =>
    quote.quote_number?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    quote.route_from?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    quote.route_to?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Stats
  const totalQuoteValue = quotes.reduce((sum, q) => sum + (Number(q.total_price) || 0), 0);
  const acceptedQuotes = quotes.filter(q => q.status === 'accepted').length;
  const pendingQuotes = quotes.filter(q => q.status === 'sent').length;

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight">Quotations</h1>
            <p className="text-sm md:text-base text-muted-foreground">Create and manage charter quotes</p>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <FileText className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Total Quotes</p>
                  <p className="text-2xl font-bold">{quotes.length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-accent/10">
                  <DollarSign className="h-5 w-5 text-accent" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Total Value</p>
                  <p className="text-2xl font-bold">${totalQuoteValue.toLocaleString()}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-success/10">
                  <FileText className="h-5 w-5 text-success" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Accepted</p>
                  <p className="text-2xl font-bold">{acceptedQuotes}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-accent/10">
                  <Clock className="h-5 w-5 text-accent" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Pending</p>
                  <p className="text-2xl font-bold">{pendingQuotes}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Content */}
        <Tabs defaultValue="quotes" className="space-y-4">
          <TabsList>
            <TabsTrigger value="quotes">Quotes</TabsTrigger>
            <TabsTrigger value="rate_cards">Rate Cards</TabsTrigger>
          </TabsList>

          {/* Quotes Tab */}
          <TabsContent value="quotes" className="space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="relative flex-1 max-w-sm">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search quotes..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-9"
                />
              </div>
              <Dialog open={isQuoteDialogOpen} onOpenChange={setIsQuoteDialogOpen}>
                <DialogTrigger asChild>
                  <Button>
                    <Plus className="h-4 w-4 mr-2" />
                    Create Quote
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-lg">
                  <DialogHeader>
                    <DialogTitle>Create New Quote</DialogTitle>
                  </DialogHeader>
                  <form onSubmit={handleCreateQuote} className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="aircraft_id">Aircraft *</Label>
                      <Select name="aircraft_id" required>
                        <SelectTrigger>
                          <SelectValue placeholder="Select aircraft" />
                        </SelectTrigger>
                        <SelectContent>
                          {aircraft.map(ac => (
                            <SelectItem key={ac.id} value={ac.id}>
                              {ac.tail_number} - {ac.aircraft_type}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="rate_card_id">Rate Card *</Label>
                      <Select name="rate_card_id" required>
                        <SelectTrigger>
                          <SelectValue placeholder="Select rate card" />
                        </SelectTrigger>
                        <SelectContent>
                          {rateCards.filter(rc => rc.is_active).map(rc => (
                            <SelectItem key={rc.id} value={rc.id}>
                              {rc.name} - ${Number(rc.hourly_rate).toLocaleString()}/hr
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="route_from">From (ICAO) *</Label>
                        <Input id="route_from" name="route_from" required placeholder="OMDB" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="route_to">To (ICAO) *</Label>
                        <Input id="route_to" name="route_to" required placeholder="EGLL" />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="departure_date">Departure Date *</Label>
                        <Input id="departure_date" name="departure_date" type="date" required />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="return_date">Return Date</Label>
                        <Input id="return_date" name="return_date" type="date" />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="passengers">Passengers</Label>
                        <Input id="passengers" name="passengers" type="number" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="flight_hours">Flight Hours *</Label>
                        <Input id="flight_hours" name="flight_hours" type="number" step="0.5" required />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="notes">Notes</Label>
                      <MentionField
                        value={quoteNotes}
                        onChange={setQuoteNotes}
                        candidates={profiles}
                        placeholder="Use @ to mention a teammate"
                      />
                    </div>
                    <Button type="submit" className="w-full" disabled={createQuote.isPending}>
                      {createQuote.isPending ? 'Creating...' : 'Create Quote'}
                    </Button>
                  </form>
                </DialogContent>
              </Dialog>
            </div>

            <div className="grid gap-4">
              {quotesLoading ? (
                <Card><CardContent className="p-8 text-center text-muted-foreground">Loading...</CardContent></Card>
              ) : filteredQuotes.length === 0 ? (
                <Card><CardContent className="p-8 text-center text-muted-foreground">No quotes found</CardContent></Card>
              ) : (
                filteredQuotes.map(quote => (
                  <Card key={quote.id} className="hover:shadow-md transition-shadow">
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between">
                        <div className="flex items-start gap-4">
                          <div className="p-3 rounded-lg bg-primary/10">
                            <FileText className="h-6 w-6 text-primary" />
                          </div>
                          <div>
                            <h3 className="font-semibold text-lg">{quote.quote_number}</h3>
                            <p className="text-sm text-muted-foreground">
                              {(quote.aircraft as any)?.tail_number} - {(quote.aircraft as any)?.aircraft_type}
                            </p>
                            <div className="flex items-center gap-4 mt-2 text-sm">
                              <span className="flex items-center gap-1">
                                <Plane className="h-3 w-3" />
                                {quote.route_from} → {quote.route_to}
                              </span>
                              <span className="flex items-center gap-1">
                                <Calendar className="h-3 w-3" />
                                {new Date(quote.departure_date).toLocaleDateString()}
                              </span>
                              {quote.flight_hours && (
                                <span className="flex items-center gap-1">
                                  <Clock className="h-3 w-3" />
                                  {quote.flight_hours}h
                                </span>
                              )}
                            </div>
                          </div>
                        </div>
                        <div className="text-right">
                          <Badge className={getStatusColor(quote.status || 'draft')}>
                            {quote.status}
                          </Badge>
                          <p className="text-xl font-bold text-accent mt-2">
                            ${Number(quote.total_price).toLocaleString()}
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </TabsContent>

          {/* Rate Cards Tab */}
          <TabsContent value="rate_cards" className="space-y-4">
            <div className="flex justify-end">
              <Dialog open={isRateCardDialogOpen} onOpenChange={setIsRateCardDialogOpen}>
                <DialogTrigger asChild>
                  <Button>
                    <Plus className="h-4 w-4 mr-2" />
                    Add Rate Card
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-lg">
                  <DialogHeader>
                    <DialogTitle>Add New Rate Card</DialogTitle>
                  </DialogHeader>
                  <form onSubmit={handleCreateRateCard} className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="name">Name *</Label>
                        <Input id="name" name="name" required placeholder="e.g., G650 Standard" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="aircraft_type">Aircraft Type</Label>
                        <Input id="aircraft_type" name="aircraft_type" placeholder="e.g., G650" />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="hourly_rate">Hourly Rate ($) *</Label>
                        <Input id="hourly_rate" name="hourly_rate" type="number" required />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="minimum_hours">Minimum Hours</Label>
                        <Input id="minimum_hours" name="minimum_hours" type="number" defaultValue={2} />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="repositioning_fee">Repositioning Fee ($)</Label>
                        <Input id="repositioning_fee" name="repositioning_fee" type="number" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="crew_overnight_rate">Crew Overnight ($)</Label>
                        <Input id="crew_overnight_rate" name="crew_overnight_rate" type="number" />
                      </div>
                    </div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="fuel_surcharge_percent">Fuel Surcharge (%)</Label>
                        <Input id="fuel_surcharge_percent" name="fuel_surcharge_percent" type="number" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="landing_fee_estimate">Landing Fee ($)</Label>
                        <Input id="landing_fee_estimate" name="landing_fee_estimate" type="number" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="handling_fee_estimate">Handling Fee ($)</Label>
                        <Input id="handling_fee_estimate" name="handling_fee_estimate" type="number" />
                      </div>
                    </div>
                    <Button type="submit" className="w-full" disabled={createRateCard.isPending}>
                      {createRateCard.isPending ? 'Creating...' : 'Create Rate Card'}
                    </Button>
                  </form>
                </DialogContent>
              </Dialog>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {rateCardsLoading ? (
                <Card><CardContent className="p-8 text-center text-muted-foreground">Loading...</CardContent></Card>
              ) : rateCards.length === 0 ? (
                <Card className="col-span-full"><CardContent className="p-8 text-center text-muted-foreground">No rate cards found</CardContent></Card>
              ) : (
                rateCards.map(rc => (
                  <Card key={rc.id} className="hover:shadow-md transition-shadow">
                    <CardHeader className="pb-2">
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-lg">{rc.name}</CardTitle>
                        <Badge variant={rc.is_active ? 'default' : 'secondary'}>
                          {rc.is_active ? 'Active' : 'Inactive'}
                        </Badge>
                      </div>
                      {rc.aircraft_type && (
                        <p className="text-sm text-muted-foreground">{rc.aircraft_type}</p>
                      )}
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Hourly Rate</span>
                          <span className="font-semibold text-accent">${Number(rc.hourly_rate).toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Min Hours</span>
                          <span>{rc.minimum_hours}h</span>
                        </div>
                        {Number(rc.repositioning_fee) > 0 && (
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Repositioning</span>
                            <span>${Number(rc.repositioning_fee).toLocaleString()}</span>
                          </div>
                        )}
                        {Number(rc.fuel_surcharge_percent) > 0 && (
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Fuel Surcharge</span>
                            <span>{rc.fuel_surcharge_percent}%</span>
                          </div>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
